init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1 -config Release -label alpha -build $env:APPVEYOR_BUILD_NUMBER -CommitId $env:APPVEYOR_REPO_COMMIT

clone_depth: 1

test: off

artifacts:
- path: artifacts\**\*.nupkg
  name: MyGet

deploy:
- provider: NuGet
  server: https://www.myget.org/F/maxfire-prelude/api/v2/package
  api_key:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB
  skip_symbols: true
  artifact: MyGet
