image: Visual Studio 2017

environment:
  github_password:
    secure: MSpb924hdiyXPSuUSzWG/w==
  # MyGet apikey
  CI_DEPLOYMENT_API_KEY:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB
  # Nuget.org apikey
  DEPLOYMENT_API_KEY:
    secure: DInFdMch2u8btkaNWMOPYOsnV6eknvY0rJvdxIkCi3Sijxc+b6i8a7142SbWtzBK

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Module VSSetup -Scope CurrentUser -Force

build_script:
  - ps: .\build.ps1 -target AppVeyor -config Debug
  - ps: .\build.ps1 -target AppVeyor -config Release

test: off

deploy: off
